sudo: required
dist: trusty
install:
- sudo apt-get -y install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
  texlive-fonts-extra tex4ht chktex
script:
- make
deploy:
  provider: s3
  access_key_id: AKIAILUSIQQRDIX2UQGQ
  secret_access_key:
    secure: lSwAceiMX/aJbuRJS5tJgcefDN0Q4nvZDrocT3o/E+p36AE6SeoBYXlBGHGed41J6sBx+3KPUsEs2QqWhZgaoNKHL0J3jb826PCVCdgRNRBmj48OtoyR6dHQ/mHBR8WZ6uLFO4egGULWA/iu6gWhu04Y25R1Tobauxi04Zp/KxYuFAenkOw3pimI+2KxXAJbGVP54AKPfESqrTZxfAAo3yTCpB0hTVbC2hdYDCsKsJPr2CAeScnOLUZEBEkH6B759aNUDY2UmjaE6p8WzJvSvk7Arv8fpSbl8JldDvVDRv05JexQ1cLG/3RzF4pMQHBmhXAf9RVUFV04bB0BjtP3sNrb6nOT/X5L0BemVpZ9kNpXMJfPSxqlIP7z/o8yL2y/LHmgXeAYqSAlMWmLyVaXst20WnUnlFDIhhzmFYIpawhEnOCBHp1v0Vwog13WrcMDZJWCAcw8Bnneegfo4n4JnTzRpb/Jv+1JJpJd5GZnWGEu3VhqXbD08YWpjgF3dFe+WrQi2jEIdnL4Vft+OR4t3XtIxa+SP3W9jSp5MZVSusZWvi+S3vzfbo7CyOf6bfYWf/lHxS24amGQ58H7pFQT3UbYpq6xOls4KnVc3pfS/ZZJzVa588kpjp0ZkQXirUHHvSkLR4ANnB9r8LvTtRFhV8rsB3yllWRsoCB9+GqOkQE=
  bucket: cat-high-perf-teams
  local-dir: out
  acl: public_read
  skip_cleanup: true
  on:
    repo: couragelabs/cat-high-perf-teams
